### INDEX action

GET http://localhost:3000/events.json


### SHOW action

GET http://localhost:3000/events/1.json


### CREATE action

POST http://localhost:3000/events.json
Content-Type: application/json

{

}


### DESTROY action

DELETE http://localhost:3000/events/1.json