@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjU3MjI2MDYxfQ.Ys9VqjNRMXgci_i6LlVTYsd_cR_W2D6GHMfMlgGQ2fA 

### INDEX action

GET http://localhost:3000/favorite_fighters.json
Authorization: Bearer {{jwt}}

### SHOW action

GET http://localhost:3000/favorite_fighters/15.json
Authorization: Bearer {{jwt}}

### CREATE action

POST http://localhost:3000/favorite_fighters.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
 "fighter_id": 15
}

### DESTROY action

DELETE http://localhost:3000/favorite_fighters/22.json
Authorization: Bearer {{jwt}}