### INDEX action

GET http://localhost:3000/favorite_fighters.json


### SHOW action

GET http://localhost:3000/favorite_fighters/2.json


### CREATE action

POST http://localhost:3000/favorite_fighters.json
Content-Type: application/json

{
 "user_id": 7,
 "fighter_id": 15
}

### DESTROY action

DELETE http://localhost:3000/favorite_fighters/18.json