### INDEX action

GET http://localhost:3000/fighters.json


### SHOW action

GET http://localhost:3000/fighters/2.json


### CREATE action

POST http://localhost:3000/fighters.json
Content-Type: application/json

{
  "name": "Miesha Tate",
  "age": "36",
  "height": "5'6",
  "weight": "125",
  "reach": "65",
  "stance": "Orthodox",
  "image": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2021-07/TATE_MIESHA_L_07-17.png?itok=l3ajmGkB",
  "video": "https://youtu.be/ipXNP1JjZY4",
  "win": "19",
  "loss": "8",
  "draw": "0",
  "organization": "UFC"
}

### UPDATE action

PATCH http://localhost:3000/fighters/4.json
Content-Type: application/json

{
  "image": "https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2021-06/GAMROT_MATEUSZ_L_04-10.png?itok=cpq3LKCx"
}
 
 
### DELETE action
DELETE http://localhost:3000/fighters/13.json
