### INDEX action

GET http://localhost:3000/fight_nights.json

### SHOW action

GET http://localhost:3000/fight_nights/1.json

### CREATE action

POST http://localhost:3000/fight_nights.json
Content-Type: application/json

{

}

### DESTROY action
DELETE http://localhost:3000/fight_nights/1.json