### INDEX action

GET http://localhost:3000/live_streams.json

### SHOW action

GET http://localhost:3000/live_streams/1.json

### CREATE action

POST http://localhost:3000/live_streams.json
Content-Type: application/json

{
  "url": "https://www.youtube.com/user/UFC/videos",
  "event_id": 3
}

### DESTROY action

DELETE http://localhost:3000/live_streams/3.json
