### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Colin Brown",
  "timezone":"PT",
  "email": "colinbrown@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users SHOW action

GET http://localhost:3000/users/7.json

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "colinbrown@test.com",
  "password": "password"
}


#Authorization: Bearer